# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Mehbubul Hasan Al-Quvi
title: Researcher | Prospective Grad Student | Engineer
email: quvi007 [at] gmail [dot] com
# email_title: 
# phone: +88 01877828385
# phone_title: Phone (Phone title override)
# website: quvi007.github.io
# website_title: Web (Website title override)
cv: files/Quvi_CV.pdf
cv_title: Curriculum vitae

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username:  quvi007
# stackoverflow_username: ""
linkedin_username: mehbubul-hasan-al-quvi-b97072275

# Additional icon links
# additional_links:
# - title: Google Scholar
#   icon: fas fa-graduation-cap
#   url: 
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/quvi.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, <b>Quvi</b> here. 
  I am a systems research intern at <a href="https://orderlab.io">OrderLab</a>, 
  <a href="https://www.umich.edu/">University of Michigan, Ann Arbor</a>. 
  My research interests lie in the intersection of Operating Systems, Storage Systems, Computer Architecture, Compilers, and System Security.
  My current research focuses on reliable kernel extensibility, and binary lifting, recompilation frameworks for security. I am a recent graduate from the Department
  of Computer Science and Engineering, <a href="https://www.buet.ac.bd/">Bangladesh University of Engineering and Technology (BUET)</a>.
  
  Currently, I am looking for a Ph.D. position in OS/Architecture/Compilers/Security.
  
content:
  - title: Research Papers # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        sub_title: Yiming Xiang, Wanning He, Mehbubul Hasan Al-Quvi, and Peng Huang
        link: 
        link_text: <mark>Paper Link</mark>
        caption: Submitted to 19th USENIX Symposium on Operating Systems Design and Implementation (OSDI 2025) - CORE Rank <b>A*</b>
        description: | # this will include new lines to allow paragraphs
          <h4><b>
            A Framework for Adding Runtime-Checks in eBPF Programs
          </b></h4><br>

          <p style="text-align: center">
            <img align="center" src="images/eBPF.png" alt="ePass" height="300"/>
          </p>

      - layout: left
        sub_title: Mehbubul Hasan Al-Quvi, Shamit Fatin, Sukarna Barua, and Anindya Iqbal
        link: 
        link_text: <mark>Paper Link</mark>
        caption: Under evaluation at <a href="https://research.samsung.com/srbd" target="_blank">Samsung Research Bangladesh (SRBD)</a>
        description: | # this will include new lines to allow paragraphs
          <h4><b>
            LELANTE: LEveraging LLM for Automated ANdroid Test Execution
          </b></h4><br>

          <p style="text-align: center">
            <img align="center" src="images/LELANTE_EXEC.png" alt="LELANTE_EXEC" height="300"/>
          </p>

          <details>
          <summary><p>⮞ Details</p></summary>
          <p>
          Automated mobile application testing faces two critical challenges: 
            (1) executing natural language test specifications without manual scripting, 
            and (2) reliably verifying test outcomes across diverse application states. 
            Existing approaches often require specialized scripting languages or 
            rely on fragile record-and-replay mechanisms, which increase maintenance 
            costs and reduce verification reliability. To address these issues, 
            we introduce LELANTE, a novel framework that leverages large language models (LLMs) 
            to automate both execution and verification of natural language test cases. 
            LELANTE employs a two-stage pipeline: an LLM interprets and executes test 
            steps via interaction with the device's graphical user interface (GUI), 
            while another language model validates execution outcomes against expected conditions. 
            In experiments across 390 test cases spanning 10 popular Android applications, 
            LELANTE achieved an <b>85%</b> execution success rate and an <b>85%</b> verification 
            accuracy using open-source models on standard hardware. 
            These results show that LLMs can effectively bridge the gap between natural language 
            test specifications and automated test execution, 
            making mobile testing more accessible without compromising reliability.
          </p>
          </details>

      - layout: left
        sub_title: H.A.Z. Sameen Shahgir, Mehbubul Hasan Al-Quvi, Shamit Fatin, Sukarna Barua, and Anindya Iqbal
        link: 
        link_text: <mark>Paper Link</mark>
        caption: Under preparation for submission to Autonomous Agents and Multi-Agent Systems (AAMAS 2025)
        description: | # this will include new lines to allow paragraphs
          <h4><b>
            DistilAgent: Distilling Agentic Capabilities from Large Language Models for Long-Horizon UI Navigation
          </b></h4><br>

          <p style="text-align: center">
            <image align="center" src="images/DistilAgent.png" alt="DistilAgent" height="300"/>
          </p>

          <details>
          <summary><p>⮞ Details</p></summary>
          <p>
          Large Language Models (LLMs) have shown remarkable potential as autonomous 
          agents in diverse environments, but their agentic capabilities are 
          strongly contingent on their parameter count and context window size. 
          While closed-source LLMs such as GPT-4 and Claude are already quite capable, 
          smaller open-source models struggle with autonomous UI navigation tasks. 
          To bridge this gap, we propose DistilAgent, a novel framework that 
          distills the capabilities of long-context closed-source LLMs into smaller models
          , significantly improving their performance in autonomous UI navigation. 
          DistilAgent incorporates three key components: task discretization to 
          break down long-horizon tasks into smaller sub-tasks that fit within the 
          context window of smaller models, explicit reasoning enforcement to ensure 
          the LLM reasons about grounding and the current state of the environment, 
          and exploration encouragement to prompt the LLM to explore the UI when 
          required actions are not immediately available on the current screen. 
          Our results demonstrate that DistilAgent improves the task completion rate 
          of GPT4 from 50% to 90%. We collected AutoNav1K - a synthetic dataset of 
          1,000 GPT4 task executions using DistilAgent. After finetuning on AutoNav1K, 
          the task completion rate of LLaMA-3.1-8B improved from 0% to 60%. DistilAgent 
          showcases the potential for distilling the agentic capabilities of large, 
          closed-source LLMs into smaller models, democratizing access to high-performance 
          autonomous UI navigation.
          </p>
          </details>

  - title: Experience
    layout: list
    content:
      - layout: left
        title: Research Intern
        caption: June 2024 - Present (Remote)
        link: https://orderlab.io
        # quote: >
        #   Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Advised by Professor Ryan (Peng) Huang

          [Ordered Systems Lab, U-M](http://orderlab.io)
      
      - layout: left
        title: Systems Researcher
        caption: January 2025 - Present
        link: https://cse.buet.ac.bd
        # quote: >
        #   Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          EDGE Research Laboratory (EdgeLab@BUET)

          Department of Computer Science and Engineering, BUET

      - layout: left
        title: Research Assistant
        caption: February 2024 - December 2024
        link: https://cse.buet.ac.bd
        # quote: >
        #   Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          SAMSUNG Applied Machine Learning Research Laboratory (SRBDLab@BUET)

          Room 901, ECE Building, BUET

  - title: Education
    layout: list
    content:
      - layout: left
        title: Bachelor of Science 
        # sub_title: Lecturer
        caption: April 2019 - July 2024
        # link: https://buet.ac.bd
        # quote: >
        #   Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Computer Science and Engineering

          Bangladesh University of Engineering and Technology (BUET)

          Thesis: *Analyzing Large Language Models in Low-Resource Settings*
          

  - title: Grants and Fellowships
    layout: text
    content: | # this will include new lines to allow paragraphs
      * Selected for RISE Research Grant 2023-24
      * Selected for High Profile ICT Scholar Fellowship 2023-24

  - title: Awards and Honors
    layout: text
    content: | # this will include new lines to allow paragraphs
      * Runner Up Student Poster Award - RISE Research Grant, 2023
      * 2nd Placed Team (BUET Novices) - Intra-BUET Programming Contest, 2019

  - title: News
    layout: text
    content: | # this will include new lines to allow paragraphs
      * **[Jan 2025]** Started as a Systems Engineer at EdgeLab, BUET.
      * **[Dec 2024]** Left Samsung Applied Machine Learning Research Laboratory, BUET.
      * **[Jun 2024]** Started as a Remote Research Intern at OrderLab, U-M.
      * **[Jun 2024]** Defended my Bachelor's thesis. Thanks to my supervisor.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
    In my spare time, I love exploring new frameworks, programming languages, and Linux distributions. I enjoy building small apps, software, and scripts for personal use. | 
    I became a self-taught programmer during my teenage years, driven by curiosity and a passion for learning. My coding journey began at 13 when I ran my first C program. Back in 2012, as a 7th grader, I was captivated by web development—creating websites with HTML, CSS, JavaScript, jQuery, and PHP. That same year, I delved into C programming, followed by JavaScript, Java, Android Development, Visual Basic.NET, C#, SQL, and more. I even experimented with game development in Unity but quickly lost interest, shifting my focus to Security and Penetration Testing.|
    During high school, two of my most significant projects were a Remote Administration Tool and an Android app for emergency situations: EmerApp. My passion for problem-solving and software development continued to grow, and in 2018, I secured the 8th position in the BUET admission test.|
    C/C++ remains my most favorite programming language for building system softwares. For web development, I prefer the PERN stack. JavaScript is also my favorite, and I enjoy using it for both frontend development and Node.js applications. Currently, I'm working on a hobby project, Project Algorist, which aims to make learning data structures and algorithms more accessible for the newcomer community—completely free. I actively solve problems on AtCoder, store my projects on GitHub, and love reading e-books from The Pragmatic Programmers.|
    My other hobbies are reading books, watching movies, and playing video games. I'm a huge fan of the DC Comics and the Mr. Robot series. I also enjoy playing games like GTA San Andreas, GTA V and Call of Duty. I'm a big fan of the Call of Duty series and have played every game in the franchise.

      <div style="width: 150px; height: 150px; overflow: hidden; display: inline-block;">
        <div style="transform: scale(1); transform-origin: top left;">
            <script type="text/javascript" id="clstr_globe" src="//clustrmaps.com/globe.js?d=mKLyIjWT577bDc9kAESkC_hHaxcXtAD5mKvhZGFApHQ"></script>
        </div>
      </div>

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
